In [2]:
import numpy as np

In [3]:
l=[1,2,3,4]
type(l)

list

In [4]:
np.array(l)

array([1, 2, 3, 4])

In [5]:
arr = np.array(l)

arr

In [6]:
type(arr)

numpy.ndarray

In [7]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# To create numpy arrays using functions
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
# Create a numpy array having either '0' or '1'
np.ones((2, 5)) # 2D '''rows, columns'''

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.zeros(5) # 1D

array([0., 0., 0., 0., 0.])

In [12]:
np.linspace(0, 10, 11) # 11 evenly spaced numbers between 0 to 10 (including 10)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.eye(3) # creates an identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.random.rand(1) # all the numbers will lie between 0 and 1, including 0 excluding 1

array([0.88561976])

In [15]:
np.random.rand(5, 2) # creates a shape, in this case "5 1D arrays having 6 columns each"

array([[0.0735297 , 0.65099643],
       [0.12187438, 0.25560683],
       [0.6622807 , 0.10814481],
       [0.812371  , 0.53062321],
       [0.09373301, 0.77994744]])

In [16]:
np.random.randn(10) # -ve numbers can be present
                    # values closer to 0 have a higher probability of being displayed

array([ 0.31070751,  0.97008421,  1.18630921,  1.02265726,  0.12722127,
       -0.89281247, -0.77568391,  1.27769914,  0.45797136, -0.39078965])

In [17]:
np.random.randn(2, 3)

array([[ 0.82852302, -2.27979544,  0.06070027],
       [-1.01282773, -0.31830813, -1.11151977]])

In [18]:
np.random.randint(0, 101, 2) # (start, end, no. of elements)

array([74, 76])

In [19]:
np.random.randint(0, 101, 5)

array([34, 43, 20, 44, 34])

In [20]:
np.random.randint(0, 101, (2, 3))

array([[86, 71, 75],
       [31,  4, 83]])

In [21]:
np.random.seed(42) # allows us create a set of random numbers
np.random.rand(4)  # 42 is an arbitrary number, any can be used

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr = np.arange(0, 25)

In [23]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr = np.random.randint(0, 101, 10)

In [25]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [26]:
ranarr.max()

99

In [27]:
ranarr.min()

2

In [28]:
ranarr.argmax() # tells max value's index

5

In [29]:
ranarr.argmin() # tells min value's index

7

In [30]:
ranarr.dtype # tells the datatype of elements in the array

dtype('int32')

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr.shape

(25,)

In [33]:
arr = arr.reshape(5, 5)

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.shape

(5, 5)

In [36]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [37]:
#Indexing
arr = np.arange(0, 11)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[8]

8

In [40]:
arr[1:5]

array([1, 2, 3, 4])

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
#broadcasting

In [45]:
arr[:5] = 100 # first 5 values get the same value as assigned

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr = np.arange(0, 11)

In [48]:
slice_of_arr = arr[:5]

In [49]:
slice_of_arr[:] = 99

In [50]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [51]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [52]:
arr_copy = arr.copy()

In [53]:
arr_copy[:] = 100

In [54]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [55]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [56]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [57]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d.shape

(3, 3)

In [59]:
arr_2d[0]

array([ 5, 10, 15])

In [60]:
arr_2d[1][1] # To find 25

25

In [61]:
#alternative
arr_2d[1, 1] # to find 25

25

In [62]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [63]:
arrr = np.arange(1, 11)

In [64]:
arrr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arrr > 7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [66]:
bool_arr = arrr > 7 # this array displays True or False depending on the condition

In [67]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [68]:
arrr[bool_arr] # Only displays where condition is True

array([ 8,  9, 10])

In [69]:
#simplified
arrr[arrr > 7]

array([ 8,  9, 10])

In [71]:
#Coding Exercise 2
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_rolls_over_two = len(dice_rolls[dice_rolls > 2])
    


In [72]:
total_rolls_over_two

19

In [73]:
arr = np.arange(0, 10)

In [74]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr + 5 # 5 will be added to each element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [77]:
arr / arr # 0/0 gives nan

C:\Users\Tejasv\AppData\Local\Temp/ipykernel_23412/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [78]:
1 / arr # 1/0 gives infinity, rest values will be displayed

C:\Users\Tejasv\AppData\Local\Temp/ipykernel_23412/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [79]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [82]:
np.log(arr)

C:\Users\Tejasv\AppData\Local\Temp/ipykernel_23412/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [83]:
arr.sum()

45

In [84]:
arr.mean()

4.5

In [85]:
arr.var() # variance

8.25

In [86]:
arr.std() # standard variation

2.8722813232690143

In [98]:
arr2d = np.arange(25).reshape(5, 5)

In [99]:
arr2d.sum()

300

In [100]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
arr2d[1:2][:].sum() # gives the sum of elements in first row

35

In [110]:
arr2d.sum(axis = 0) # gives the sum down the rows or sum of the entire column

array([50, 55, 60, 65, 70])

In [112]:
arr2d.sum(axis = 1) # gives the sum across each column or sum of the entire row

array([ 10,  35,  60,  85, 110])

In [ ]:
#Numpy Exercises

In [113]:
import numpy as np

In [114]:
# Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [115]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [117]:
fivearray = np.zeros(10)

In [118]:
fivearray[:] = 5

In [119]:
fivearray

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [121]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [122]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [123]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [124]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
arr = np.random.seed(42)

In [129]:
arr

In [130]:
np.linspace(0,1,101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [131]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [132]:
mat = np.arange(1, 26).reshape(5, 5)

In [133]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [134]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [135]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [137]:
mat[4]

array([21, 22, 23, 24, 25])

In [139]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [140]:
mat.sum()

325

In [142]:
mat.std()

7.211102550927978

In [144]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [145]:
np.random.randn(25)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
        1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272])

In [161]:
np.random.rand(1)

array([0.6852195])

In [170]:
np.random.seed(42)
np.random.rand(1)

array([0.37454012])

0